// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftCandy.Data;

namespace SoftCandy.Migrations
{
    [DbContext(typeof(SoftCandyContext))]
    [Migration("20220521225932_SoftCandy")]
    partial class SoftCandy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SoftCandy.Models.Caixa", b =>
                {
                    b.Property<int>("IdCaixa")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataHoraAbertura");

                    b.Property<DateTime>("DataHoraFechamento");

                    b.Property<bool>("EstaAberto");

                    b.Property<int>("FuncionarioAberturaId");

                    b.Property<int>("FuncionarioFechamentoId");

                    b.Property<decimal>("ValorDinheiroAbertura")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("ValorOperacoesEntrada")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("ValorOperacoesSaida")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("ValorTotalFechamentoDinheiro")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("ValorTotalOperacoes")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("ValorTotalVendas")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("ValorVendasCartaoCredito")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("ValorVendasCartaoDebito")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("ValorVendasDinheiro")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("ValorVendasPix")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("IdCaixa");

                    b.HasIndex("FuncionarioAberturaId");

                    b.HasIndex("FuncionarioFechamentoId");

                    b.ToTable("Caixa");
                });

            modelBuilder.Entity("SoftCandy.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AtivoCategoria");

                    b.Property<string>("NomeCategoria");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("SoftCandy.Models.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataHoraCriacao");

                    b.Property<DateTime>("DataHoraRecebimento");

                    b.Property<int>("FormaPagamento");

                    b.Property<int>("IdCaixa");

                    b.Property<bool>("Recebido");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCaixa");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("SoftCandy.Models.Fornecedor", b =>
                {
                    b.Property<int>("IdFornecedor")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AtivoFornecedor");

                    b.Property<string>("BairroFornecedor");

                    b.Property<string>("CelularFornecedor");

                    b.Property<string>("CidadeFornecedor");

                    b.Property<string>("Cnpj");

                    b.Property<string>("EmailFornecedor");

                    b.Property<string>("EstadoFornecedor");

                    b.Property<string>("LogradouroFornecedor");

                    b.Property<string>("NomeFantasia");

                    b.Property<string>("NumeroFornecedor");

                    b.Property<string>("RazaoSocial");

                    b.HasKey("IdFornecedor");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("SoftCandy.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<string>("Bairro");

                    b.Property<int>("Cargo");

                    b.Property<string>("Celular");

                    b.Property<string>("Cidade");

                    b.Property<string>("Email");

                    b.Property<string>("Estado");

                    b.Property<string>("Logradouro");

                    b.Property<string>("Nome");

                    b.Property<string>("Numero");

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("SoftCandy.Models.ItemComanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IdComanda");

                    b.Property<int>("IdLote");

                    b.Property<int>("Quantidade");

                    b.HasKey("Id");

                    b.HasIndex("IdComanda");

                    b.HasIndex("IdLote");

                    b.ToTable("ItemComanda");
                });

            modelBuilder.Entity("SoftCandy.Models.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<DateTime>("DataHoraFabricacao");

                    b.Property<DateTime>("DataHoraValidade");

                    b.Property<int>("IdProduto");

                    b.Property<decimal>("PrecoCompra")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("QuantidadeEstoque");

                    b.HasKey("Id");

                    b.HasIndex("IdProduto");

                    b.ToTable("Lote");
                });

            modelBuilder.Entity("SoftCandy.Models.OperacaoCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataHora");

                    b.Property<string>("Descricao");

                    b.Property<int>("IdCaxa");

                    b.Property<int>("IdFuncionario");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int>("Tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCaxa");

                    b.HasIndex("IdFuncionario");

                    b.ToTable("OperacaoCaixa");
                });

            modelBuilder.Entity("SoftCandy.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<int>("IdCategoria");

                    b.Property<int>("IdFornecedor");

                    b.Property<int>("Medida");

                    b.Property<string>("Nome");

                    b.Property<int>("QuantidadeDecremento");

                    b.Property<int>("QuantidadeDescartada");

                    b.Property<int>("QuantidadeMinima");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdFornecedor");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("SoftCandy.Models.Caixa", b =>
                {
                    b.HasOne("SoftCandy.Models.Funcionario", "FuncionarioAbertura")
                        .WithMany()
                        .HasForeignKey("FuncionarioAberturaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SoftCandy.Models.Funcionario", "FuncionarioFechamento")
                        .WithMany()
                        .HasForeignKey("FuncionarioFechamentoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SoftCandy.Models.Comanda", b =>
                {
                    b.HasOne("SoftCandy.Models.Caixa", "Caixa")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCaixa")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SoftCandy.Models.ItemComanda", b =>
                {
                    b.HasOne("SoftCandy.Models.Comanda", "Comanda")
                        .WithMany("ItensPedidos")
                        .HasForeignKey("IdComanda")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SoftCandy.Models.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("IdLote")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SoftCandy.Models.Lote", b =>
                {
                    b.HasOne("SoftCandy.Models.Produto", "Produto")
                        .WithMany("Lotes")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SoftCandy.Models.OperacaoCaixa", b =>
                {
                    b.HasOne("SoftCandy.Models.Caixa", "Caixa")
                        .WithMany("Operacoes")
                        .HasForeignKey("IdCaxa")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SoftCandy.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SoftCandy.Models.Produto", b =>
                {
                    b.HasOne("SoftCandy.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SoftCandy.Models.Fornecedor", "Fornecedor")
                        .WithMany("Produtos")
                        .HasForeignKey("IdFornecedor")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
